@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjUzNDUyNTMwLCJpYXQiOjE2NTI4NDc3MzAsImp0aSI6IjFkZTFjNTAyODYxNjRlYTJhNDIyNGVmNWMyMjc2OGYyIiwidXNlcl9pZCI6MTI2fQ._zoNzt2O4mZzFgRxwxflAIMYIsTfnb2GsQx6f6EbxxE

GET http://178.128.110.188/api/v1/wishlist/get?current_page=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}